### ISSUE TITLE
Issue about symmetric matrix during clustering

### ISSUE THREAD

**Issue by skarlosdeus** [ameyagodbole/Prob-CBR#3]
Hello team,

Initially i would like to thank you for this repository. 

I face the next issue: when i examine one of my own datasets, the clustering process does not work, taking the next message:

'ValueError: Distance matrix 'X' must be symmetric.'

I have manually augment the edges so as to contain the inverse relations and follow the steps as in your case. Shouldn't the distances format automatically a symmetric matrix?

Thanks in advance.

**Comment by ameyagodbole** [comment]
Hi,
Can you specify the exact line where this error is raised? A full stack trace would be better.

**Comment by skarlosdeus** [comment]
[2021-11-08 12:06:15 	 Clustering entities with linkage = 0.25...]
Traceback (most recent call last):
  File "prob_cbr/pr_cbr.py", line 862, in <module>
    main(args)
  File "prob_cbr/pr_cbr.py", line 754, in main
    args.cluster_assignments = cluster_entities(adj_mat, args.linkage)
  File "/home/scarlos/Documents/git/reasoning/Prob-CBR-main/prob_cbr/clustering/entity_clustering.py", line 27, in cluster_entities
    zavg = linkage(squareform(dists), method='average')
  File "/home/scarlos/anaconda3/envs/seal/lib/python3.6/site-packages/scipy/spatial/distance.py", line 2184, in squareform
    is_valid_dm(X, throw=True, name='X')
  File "/home/scarlos/anaconda3/envs/seal/lib/python3.6/site-packages/scipy/spatial/distance.py", line 2260, in is_valid_dm
    'symmetric.') % name)
ValueError: Distance matrix 'X' must be symmetric.

**Comment by skarlosdeus** [comment]
@ameyagodbole i have solved the issue. I had to add the invert relations after the train/dev/test split. Thanks for your time.
